// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenHealthMCP.Data;

#nullable disable

namespace OpenHealthMCP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902160632_AddExtendedGarminActivityData")]
    partial class AddExtendedGarminActivityData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveLengths")
                        .HasColumnType("integer");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("AerobicTrainingEffect")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnaerobicTrainingEffect")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("AveragePaceSecondsPerKilometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("AveragePowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSwolf")
                        .HasColumnType("double precision");

                    b.Property<string>("CadenceUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElapsedDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationLossMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("HeartRateZonesSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("IntensityFactor")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("LapsSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MaxCadence")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxPowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MovingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("NormalizedPowerWatts")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<double?>("TrainingLoad")
                        .HasColumnType("double precision");

                    b.Property<double?>("TrainingStressScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Vo2Max")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityHeartRateZone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LowBoundaryBpm")
                        .HasColumnType("integer");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("ZoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "ZoneNumber")
                        .IsUnique();

                    b.ToTable("activity_heart_rate_zones", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityLap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("AveragePaceSecondsPerKilometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<string>("CadenceUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElapsedDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationLossMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("IntensityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LapIndex")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxCadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MovingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "LapIndex")
                        .IsUnique();

                    b.ToTable("activity_laps", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.DailyMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryMax")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryMin")
                        .HasColumnType("integer");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("Hrv")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("MinHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("SleepScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<double?>("StressAverage")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Date")
                        .IsUnique();

                    b.ToTable("daily_metrics", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.OAuthAuthorizationCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("oauth_authorization_codes", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.OAuthClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("oauth_clients", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.OAuthToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("oauth_tokens", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.RawProviderData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "DataType", "ExternalId")
                        .IsUnique();

                    b.ToTable("raw_provider_data", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.ToTable("sync_states", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityHeartRateZone", b =>
                {
                    b.HasOne("OpenHealthMCP.Data.Entities.Activity", "Activity")
                        .WithMany("HeartRateZones")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityLap", b =>
                {
                    b.HasOne("OpenHealthMCP.Data.Entities.Activity", "Activity")
                        .WithMany("Laps")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.Activity", b =>
                {
                    b.Navigation("HeartRateZones");

                    b.Navigation("Laps");
                });
#pragma warning restore 612, 618
        }
    }
}
