// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenHealthMCP.Data;

#nullable disable

namespace OpenHealthMCP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903080753_ExtendActivitySummary")]
    partial class ExtendActivitySummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveLengths")
                        .HasColumnType("integer");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("AerobicTrainingEffect")
                        .HasColumnType("double precision");

                    b.Property<double?>("AnaerobicTrainingEffect")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageGroundContactTimeMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("AveragePaceSecondsPerKilometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("AveragePowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageStrideLengthMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSwolf")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageVerticalOscillationMillimeters")
                        .HasColumnType("double precision");

                    b.Property<string>("CadenceUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElapsedDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationLossMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("HeartRateZonesSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("IntensityFactor")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsParent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LapsSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MaxCadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxPowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxTwentyMinutePowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MovingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("NormalizedPowerWatts")
                        .HasColumnType("double precision");

                    b.Property<string>("ParentExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StreamsSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TrainingLoad")
                        .HasColumnType("double precision");

                    b.Property<double?>("TrainingStressScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Vo2Max")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.HasIndex("Source", "ActivityType", "StartedAt");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityHeartRateZone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<int?>("LowBoundaryBpm")
                        .HasColumnType("integer");

                    b.Property<double?>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("ZoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "ZoneNumber")
                        .IsUnique();

                    b.ToTable("activity_heart_rate_zones", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityLap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<double?>("AverageCadence")
                        .HasColumnType("double precision");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("AveragePaceSecondsPerKilometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<string>("CadenceUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElapsedDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationGainMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationLossMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("IntensityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LapIndex")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxCadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaxTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("MovingDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "LapIndex")
                        .IsUnique();

                    b.ToTable("activity_laps", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivitySample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Cadence")
                        .HasColumnType("double precision");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<double?>("ElevationMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("HeartRateBpm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("PaceSecondsPerKilometer")
                        .HasColumnType("double precision");

                    b.Property<double?>("PowerWatts")
                        .HasColumnType("double precision");

                    b.Property<double?>("RespirationRate")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "ElapsedSeconds")
                        .IsUnique();

                    b.HasIndex("ActivityId", "TimestampUtc");

                    b.ToTable("activity_samples", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityStream", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string[]>("AvailableMetrics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Samples")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.ToTable("activity_streams", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.DailyMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("ActiveSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ActivityStressSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("AverageRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSleepRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSleepSpo2")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSleepStress")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageSpo2")
                        .HasColumnType("double precision");

                    b.Property<int?>("AwakeSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("BmrCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryCharged")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryDrained")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryMax")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryMin")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryMostRecent")
                        .HasColumnType("integer");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("FloorsClimbed")
                        .HasColumnType("double precision");

                    b.Property<int?>("FloorsGoal")
                        .HasColumnType("integer");

                    b.Property<double?>("HighStressPercentage")
                        .HasColumnType("double precision");

                    b.Property<int?>("HighStressSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("Hrv")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("HrvCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HrvFiveMinuteHigh")
                        .HasColumnType("double precision");

                    b.Property<string>("HrvStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("IntensityGoal")
                        .HasColumnType("integer");

                    b.Property<double?>("LatestSpo2")
                        .HasColumnType("double precision");

                    b.Property<int?>("LightSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("LowStressPercentage")
                        .HasColumnType("double precision");

                    b.Property<int?>("LowStressSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("MaximumRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MediumStressPercentage")
                        .HasColumnType("double precision");

                    b.Property<int?>("MediumStressSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("MinHeartRate")
                        .HasColumnType("integer");

                    b.Property<double?>("MinimumRespirationRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumSpo2")
                        .HasColumnType("double precision");

                    b.Property<int?>("ModerateIntensityMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("NapDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("RemSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("RestStressPercentage")
                        .HasColumnType("double precision");

                    b.Property<int?>("RestStressSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepAwakeCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SleepEndLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset?>("SleepEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SleepQualifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("SleepScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("SleepStartLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset?>("SleepStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SleepSubScoresJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("Spo2WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Spo2WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<int?>("StepsGoal")
                        .HasColumnType("integer");

                    b.Property<double?>("StressAverage")
                        .HasColumnType("double precision");

                    b.Property<double?>("StressMax")
                        .HasColumnType("double precision");

                    b.Property<string>("StressQualifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TotalIntensityMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("UnmeasurableSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UtcOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("VigorousIntensityMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WellnessEndLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset?>("WellnessEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WellnessStartLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset?>("WellnessStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Date")
                        .IsUnique();

                    b.ToTable("daily_metrics", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.DailyTimeline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("Samples")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Date", "Metric")
                        .IsUnique();

                    b.ToTable("daily_timelines", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.HealthMetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Quality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ValueNumeric")
                        .HasColumnType("double precision");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Source", "LocalDate", "Metric");

                    b.HasIndex("Source", "Metric", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("health_metric_samples", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.OAuthAuthorizationCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("oauth_authorization_codes", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.OAuthClient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("oauth_clients", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.OAuthToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("oauth_tokens", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.RawProviderData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("garmin-v0");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "DataType", "ExternalId", "FetchedAt");

                    b.HasIndex("Source", "DataType", "ExternalId", "PayloadHash")
                        .IsUnique();

                    b.ToTable("raw_provider_data", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.ToTable("sync_states", (string)null);
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityHeartRateZone", b =>
                {
                    b.HasOne("OpenHealthMCP.Data.Entities.Activity", "Activity")
                        .WithMany("HeartRateZones")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityLap", b =>
                {
                    b.HasOne("OpenHealthMCP.Data.Entities.Activity", "Activity")
                        .WithMany("Laps")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivitySample", b =>
                {
                    b.HasOne("OpenHealthMCP.Data.Entities.Activity", "Activity")
                        .WithMany("Samples")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.ActivityStream", b =>
                {
                    b.HasOne("OpenHealthMCP.Data.Entities.Activity", "Activity")
                        .WithOne("Stream")
                        .HasForeignKey("OpenHealthMCP.Data.Entities.ActivityStream", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("OpenHealthMCP.Data.Entities.Activity", b =>
                {
                    b.Navigation("HeartRateZones");

                    b.Navigation("Laps");

                    b.Navigation("Samples");

                    b.Navigation("Stream");
                });
#pragma warning restore 612, 618
        }
    }
}
